[build]
command = "pnpm docs:build"
publish = "docs/.vitepress/dist"

[build.environment]
NODE_VERSION = "24"
NODE_OPTIONS = "--max-old-space-size=4096"

# Deploy previews for pull requests
[context.deploy-preview]
command = "pnpm docs:build"

# Production builds
[context.production]
command = "pnpm docs:build"
