// Auto-generated by Paka - do not edit manually
import type { DefaultTheme } from 'vitepress'

export const apiSidebar: DefaultTheme.SidebarItem[] = [
  {
    'text': 'Domains',
    'items': [
      {
        'text': 'Arr',
        'link': '/api/arr',
      },
      {
        'text': 'Err',
        'link': '/api/err',
      },
      {
        'text': 'Fn',
        'link': '/api/fn',
      },
      {
        'text': 'Json',
        'link': '/api/json',
      },
      {
        'text': 'Num',
        'link': '/api/num',
      },
      {
        'text': 'Obj',
        'link': '/api/obj',
        'items': [
          {
            'text': 'Union',
            'link': '/api/obj/union',
          },
        ],
        'collapsed': true,
      },
      {
        'text': 'Prom',
        'link': '/api/prom',
      },
      {
        'text': 'Rec',
        'link': '/api/rec',
      },
      {
        'text': 'Str',
        'link': '/api/str',
        'items': [
          {
            'text': 'Char',
            'link': '/api/str/char',
          },
          {
            'text': 'Code',
            'link': '/api/str/code',
          },
          {
            'text': 'Text',
            'link': '/api/str/text',
          },
          {
            'text': 'Visual',
            'link': '/api/str/visual',
          },
        ],
        'collapsed': true,
      },
    ],
  },
  {
    'text': 'Utils',
    'items': [
      {
        'text': 'Html',
        'link': '/api/html',
      },
      {
        'text': 'Paka',
        'link': '/api/paka',
      },
      {
        'text': 'Test',
        'link': '/api/test',
        'items': [
          {
            'text': 'Test',
            'link': '/api/test/test',
          },
        ],
        'collapsed': true,
      },
      {
        'text': 'Ts',
        'link': '/api/ts',
        'items': [
          {
            'text': 'Assert',
            'link': '/api/ts/assert',
          },
          {
            'text': 'Kind',
            'link': '/api/ts/kind',
          },
          {
            'text': 'SENTINEL',
            'link': '/api/ts/sentinel',
          },
          {
            'text': 'SimpleSignature',
            'link': '/api/ts/simplesignature',
          },
          {
            'text': 'Union',
            'link': '/api/ts/union',
          },
          {
            'text': 'VariancePhantom',
            'link': '/api/ts/variancephantom',
          },
        ],
        'collapsed': true,
      },
      {
        'text': 'Value',
        'link': '/api/value',
      },
    ],
  },
]
