// Traits - exported directly at root level
export * from '#Arb'
export * from '#Eq'
export * from '#Type'

// Domains
export * from '#arr'
export * from '#arr-mut'
export * from '#bool'
export * from '#fn'
export * from '#group'
export * from '#idx'
export * from '#null'
export * from '#num'
export * from '#obj'
export * from '#prom'
export * from '#rec'
export * from '#str'
export * from '#task'
export * from '#tree'
export * from '#undefined'
export * from '#url'

// Utils
export * from '#cache'
export * from '#cli'
export * from '#codec'
export * from '#debug'
export * from '#err'
export * from '#fs'
export * from '#fs-layout'
export * from '#fs-relative'
export * from '#glo'
export * from '#http'
export * from '#json'
export * from '#lang'
export * from '#manifest'
export * from '#mask'
export * from '#name'
export * from '#package-manager'
export * from '#pat'
export * from '#path'
export * from '#ref'
export * from '#resource'
export * from '#test'
export * from '#traitor'
export * from '#ts'
export * from '#value'
export * from '#zod-aid'

// To satisfy TS
// e.g.
// The inferred type of 'create' cannot be named without a reference to '@wollybeard/kit/node_modules/.pnpm/type-fest@4.41.0/node_modules/type-fest'. This is likely not portable. A type annotation is necessary.
export type { PackageJson } from 'type-fest'
